//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Order>
    {
    	
    			public virtual int OrderID { get; set; }
    			public virtual Nullable<double> Total { get; set; }
    			public virtual Nullable<int> Status { get; set; }
    			public virtual Nullable<System.DateTime> OrderDate { get; set; }
    			public virtual Nullable<int> AccountID { get; set; }
    	
    	public OrderViewModel() : base() { }
    	public OrderViewModel(DataService.Models.Entities.Order entity) : base(entity) { }
    
    }
}
