//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.OrderItem>
    {
    	
    			public virtual int OrderItemID { get; set; }
    			public virtual Nullable<double> Price { get; set; }
    			public virtual Nullable<int> Quantity { get; set; }
    			public virtual Nullable<System.DateTime> DateCreated { get; set; }
    			public virtual Nullable<System.DateTime> DateModified { get; set; }
    			public virtual Nullable<int> ProductID { get; set; }
    			public virtual Nullable<int> OrderID { get; set; }
    	
    	public OrderItemViewModel() : base() { }
    	public OrderItemViewModel(DataService.Models.Entities.OrderItem entity) : base(entity) { }
    
    }
}
