//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Product>
    {
    	
    			public virtual int ProductID { get; set; }
    			public virtual string ProductName { get; set; }
    			public virtual Nullable<double> ProductPrice { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<System.DateTime> DateCreated { get; set; }
    			public virtual Nullable<System.DateTime> DateModified { get; set; }
    			public virtual Nullable<bool> IsActived { get; set; }
    			public virtual Nullable<bool> IsDeleted { get; set; }
    			public virtual Nullable<int> CategoryID { get; set; }
    	
    	public ProductViewModel() : base() { }
    	public ProductViewModel(DataService.Models.Entities.Product entity) : base(entity) { }
    
    }
}
