//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IOrderItemService : DataService.BaseConnect.IBaseService<OrderItem, OrderItemViewModel>
    {
    }
    
    public partial class OrderItemService : DataService.BaseConnect.BaseService<OrderItem, OrderItemViewModel>, IOrderItemService
    {
         public OrderItemService()
         {
         }
        public OrderItemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IOrderItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
