//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IsysdiagramService : DataService.BaseConnect.IBaseService<sysdiagram, sysdiagramViewModel>
    {
    }
    
    public partial class sysdiagramService : DataService.BaseConnect.BaseService<sysdiagram, sysdiagramViewModel>, IsysdiagramService
    {
         public sysdiagramService()
         {
         }
        public sysdiagramService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IsysdiagramRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
